# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-09 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Customer')),
                ('image', models.ImageField(blank=True, max_length=500, upload_to=b'', verbose_name='Image')),
                ('is_company', models.BooleanField(verbose_name='Is comapany')),
                ('mobile', models.BigIntegerField(blank=True, verbose_name='Mobile')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
        ),
    ]
